title: Tony Castrogiovanni # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  People-Focused Technologist -> Connector | Pioneer | Advocate | Teacher 
  <br><br>
  Innovative software professional, public speaker, and team leader with 15+ years of experience crafting solutions that delight customers while building trust. I currently am working as an independent software consultant partnering with clients that are interested in maximizing the value of their investments into low-code/no-code application development platforms.  If you have an opportunity you would like to discuss, connect with me on LinkedIn to explore it.
  <br><br>
  <a href="https://www.linkedin.com/in/tonycastrogiovanni/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
